### ISSUE TITLE
Face orientation not working (and other small bugs)

### ISSUE THREAD

**Issue by Ares9323** [SpectralVectors/Blunder#1]
Hi, I've discovered this amazing project just yesterday and I read 

> ! - This template is in active development ;P please report bugs - !

so I hope this is the right place to do it!

I was using version 2.92.0 so I downloaded 2.83.12 LTS to test before opening an issue.

- Mouse wheel and "numpad + and -" don't change the moving speed (Working fine in 2.8 and 2.91.2 / not workingi in 2.92 and 2.93)
- White chevron icons are not visible in light gray background (Both versions)
- Face orientation is not working at all, should change faces color depending on their normals (Both versions)
- Loop select doesn't always work with alt+left_click, you have to use alt+shif+left_click but in shortcuts there are both key-bindings (Both versions)

![image](https://user-images.githubusercontent.com/46932745/106616156-8446b880-656d-11eb-803d-bb0ffbadae80.png)

I'll keep you up to date if I find anything else relevant, tell me if I have to contact you on another channel 😊

Thank you!

**Comment by SpectralVectors** [comment]
Hi Ares, thanks for reaching out, I've been all over the place with my Blender stuff lately. I've been meaning to get back to it for some time.

The issues you mentioned are not the only ones, there are problems with Weight Painting, and a few other modes of Blender that I hadn't used as much when I started developing the add-on. When I tried to navigate with Right Click I got stuck and had to close Blender to get the cursor back.

A lot of work needs to be done to bring this up to speed with all the changes since 2.83/2.9, and it may happen, but probably not in a timely manner, unfortunately, for a couple of reasons:

One is that importing the Unreal shortcuts in Blender causes a snowball effect, whereby changing one shortcut in one mode then demands that you change a conflicting one in another mode, which then causes functionality to need to be remapped, which has consequences in one or more modes. There is no easy way to resolve keymap conflicts in Blender, there is no notification that "This is in use" or "This already mapped to this". You have to manually search each time and hope that you notice and fix every conflict. Then, compound that with the fact that as Blender updates and changes between versions they will sometimes reassign keys, or add new functions that take over mappings that had been set aside for Unreal.

Two is that I moved on to a second template I'm calling BLUI - https://spectral-vectors.itch.io/blui - I put that release up just so that you could have something to try as an alternative, if the bugs get too much to bear. 

The distinction with this one is that it starts with the Industry Compatible Keymap, which already uses many of Unreal's shortcuts by default, and I'm porting in some of Blender's more common shortcuts like Shift+A to add objects, or Numpad for viewport control. I've found that by doing it this way I can avoid a lot of the conflicts I ran into before. The biggest changes are the numbers now switch between modes, and Tab is used for Search. 

So, no more Tabbing into Edit Mode, then using 1, 2, 3 to select Vertex, Edge, Face, now you just press 2 for Edge mode straight from Object mode, then 4 to get back into Object, while 5, 6, 7, 8 are Sculpt, Vertex, Weight and Texture Paint. It's a weird adjustment at first, but one that I've come to like. It gives the interface more of a minimal appearance, lessening the number of tabs.

It's also designed to work with the addons on my Github, particularly UnrealRightClick, which causes a whole ton of conflicts with the way I set up Right Click Navigation in Blunder.

Thanks for writing, I do hope to be able to devote some more time to these projects shortly. You can write me here, or on itch, and I'll try to respond in a timely manner. It's still tricky for me to decide whether it's worth investing the time to iron out the bugs in Blunder, or if I should just focus on BLUI, but it's nice to know people still find this stuff useful!

**Comment by Ares9323** [comment]
Hi, I feel so bad for answering you after more than a month.. I flagged your mail as important but I really had few time to spend on blender this month (I don’t use it professionally, it’s just a passion so I had to prioritize my real work...)

I’ve been using “UnrealRightClick” because that’s the most important Unreal feature for me, I tried to download BLUI today because it looks very interesting but i’m having startup crashes (I’ve read i’m not the only one having problems with version 2.91.2).
If you need anything just ask me, I promise not to answer so late this time!

Thank you for your work ❤
